---
title: 'Chapter 9: Support Vector Machines'
pdf_document: default
output:
  html_notebook:
    pandoc_args:
    - --number-sections
    - --number-offset=9
    toc: yes
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

# Lab

## Support Vector Classifier

```{r}
library(e1071)
#generate observations
set.seed(1)
x <- matrix(rnorm(20*2), ncol = 2)
y <- c(rep(-1, 10), rep(1,10))
x[y==1,] <- x[y==1,] + 1
plot(x, col = (3-y))

dat <- data.frame(x = x, y = as.factor(y))
svmfit <- svm(y~., data = dat, kernel = "linear", cost = 10, scale = FALSE)
plot(svmfit, dat)

#view which vectors are the support vectors
svmfit$index
summary(svmfit)
```

```{r}
#cross validate; tune across cost levels
set.seed(1)
tune.out = tune(svm, y ~ ., data = dat, kernel = "linear", 
                ranges = list(cost = c(0.001, 0.01, 0.1, 1, 5, 10, 100)))
summary(tune.out)

# access the best model
bestmod <- tune.out$best.model
summary(bestmod)

#predict

```

## Support Vector Machine

```{r}
set.seed (1)
x=matrix(rnorm(200*2), ncol=2)
x[1:100,]=x[1:100,]+2
x[101:150,]=x[101:150,]-2
y=c(rep(1,150),rep(2,50))
dat=data.frame(x=x,y=as.factor(y))
plot(x, col = y)

train = sample(200, 100)
svmfit <- svm(y ~ ., data = dat[train,], kernel = "radial", gamma = 1, cost = 1)
plot(svmfit, dat[train,])

summary(svmfit)

#overfit the data
svmfit <- svm(y ~ ., data = dat[train,], kernel = "radial", gamma = 1, cost = 1e5)
plot(svmfit, dat[train,])

#cross validate to get best gamma and cost
tune.out <- tune(svm, y ~ ., data = dat[train,], kernel = "radial", ranges = list(cost = c(0.1, 1, 10, 100, 1000),
                                                                                  gamma = c(0.5, 1, 2, 3, 4)))
summary(tune.out)

table(true = dat[-train, "y"], pred <-  predict(tune.out$best.model, newdata = dat[-train,]))
```

## ROC Curve

```{r}
library(ROCR)
%>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% %>% 
```

